[package]
name = "rusty-neat"
version = "0.1.0"
authors = ["Joshua Allen <jallen17@illinois.edu>"]
license = "MIT"
description = "A tool to develop an artificial Fastq file"
readme = "README.md"
homepage = "https://github.com/ncsa/rusty-neat"
repository = "https://github.com/ncsa/rusty-neat"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.20"
rand = "0.8.5"
xorshift = "0.1.3"
simplelog = "^0.12.0"
chrono = "0.4.34"
clap = { version = "4.5.1", features = ["derive"] }
serde = { version = "1.0.188", features = ["derive"] }
serde_yaml = "0.9.32"
