[package]
name = "rusty-neat"
version = "0.2.0"
edition = "2021"
authors = ["Joshua Allen <jallen17@illinois.edu>"]

[dependencies]
rand = "0.8.5"
log = "0.4.21"
xorshift = "0.1.3"
chrono = "0.4.34"
simplelog = "0.12.1"
serde_yaml = "0.9.32"
clap = { version = "4.5.1", features = ["derive"] }
itertools = "0.12.1"
assert_fs = "1.1.1"
serde_json = "1.0.114"
serde = { version = "1.0.197", features = ["derive"] }
simple_rng = { path = "simple_rng" }
statrs = "0.17.1"