[package]
name = "rusty_neat"
version = "0.1.0"
authors = ["Joshua Allen <jallen17@illinois.edu>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.20"
rand = "0.8.5"
simplelog = "^0.12.0"
xorshift = "0.1.3"
