reference: test_data/ecoli.fa
read_len: 10
coverage: 3

mutation_rate: 0.001
rng_seed: null

ploidy: 9
paired_ended: true
fragment_mean: 10.0
fragment_st_dev: 11.0

produce_fastq: true
produce_bam: true
produce_vcf: true
produce_fasta: true

overwrite_output: true
output_dir: /tmp/test_output
output_prefix: ecoli
