reference: test_data/ecoli.fa
read_len: 150
coverage: 5

def_mutation_rate: 0.001
mutation_model: models/mut_model.yml
rng_seed: null

ploidy: 2
paired_ended: true
fragment_mean: 300.0
fragment_st_dev: 30.0

produce_fastq: true
produce_bam: false
produce_vcf: true
produce_fasta: true

overwrite_output: true
output_dir: /tmp/test_output
output_prefix: ecoli
