mut_rates: null
mut_probabilities:
  p:
    Del: 0.25
    Snp: 0.5
    Ins: 0.25
snp_model:
  a:
    cumulative_weights:
    - 0.0
    - 0.17
    - 0.86
    total_weight: 1.0
    weight_distribution:
      low: 0.0
      scale: 1.0
  c:
    cumulative_weights:
    - 0.16
    - 0.16
    - 0.33
    total_weight: 1.0
    weight_distribution:
      low: 0.0
      scale: 1.0
  g:
    cumulative_weights:
    - 0.67
    - 0.8400000000000001
    - 0.8400000000000001
    total_weight: 1.0
    weight_distribution:
      low: 0.0
      scale: 1.0
  t:
    cumulative_weights:
    - 0.14
    - 0.83
    - 0.99
    total_weight: 0.99
    weight_distribution:
      low: 0.0
      scale: 0.99
ins_model:
  length:
    cumulative_weights:
    - 0.25
    - 0.5
    - 0.75
    total_weight: 1.0
    weight_distribution:
      low: 0.0
      scale: 1.0
del_model:
  length:
    cumulative_weights:
    - 0.25
    - 0.5
    - 0.75
    total_weight: 1.0
    weight_distribution:
      low: 0.0
      scale: 1.0
